### ISSUE TITLE
java.lang.NullPointerException with checkout changelog:false

### ISSUE THREAD

**Issue by nathan-murphy** [jenkinsci/accurev-plugin#96]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Jenkins: 2.319.2
OS: Windows Server 2016 - 10.0
---
accurev:0.7.25-SNAPSHOT (private-2de3ef85-320007054)
ace-editor:1.1
additional-metrics:1.3
analysis-model-api:10.9.1
ant:1.13
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.15.2
authentication-tokens:1.4
authorize-project:1.4.0
blackduck-detect:7.0.0
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-history-metrics-plugin:93.v0e17adc6ccea
build-monitor-plugin:1.13+build.202201221819
build-name-setter:2.2.0
build-timestamp:1.0.3
build-token-root:1.9
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:751.vda_24678a_f781
cloudbees-folder:6.17
cobertura:1.17
code-coverage-api:2.0.4
command-launcher:1.6
conditional-buildstep:1.4.1
config-file-provider:3.8.2
configuration-as-code:1.55.1
copyartifact:1.46.2
credentials:1074.v60e6c29b_b_44b_
credentials-binding:1.27.1
cvs:2.19
data-tables-api:1.11.3-6
display-url-api:2.3.5
docker-commons:1.18
docker-workflow:1.27
doxygen:0.18
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
email-ext:2.87
envinject-api:1.8
exclusive-execution:0.8
external-monitor-job:189.v849257a_0d3a_c
favorite:2.3.3
font-awesome-api:5.15.4-5
forensics-api:1.7.0
fortify:21.2.37
fstrigger:0.42
git:4.10.3
git-client:3.11.0
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
global-build-stats:1.5
gradle:1.38
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.28
ivy:2.1
jackson2-api:2.13.1-246.va8a9f3eaf46a
javadoc:1.6
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jdk-tool:1.5
jenkins-design-language:1.25.2
jjwt-api:0.11.2-9.c8b45b8bb173
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
klocwork:2021.3.1
ldap:2.7
lockable-resources:2.13
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
mask-passwords:3.0
matrix-auth:3.0.1
matrix-project:1.20
maven-plugin:3.16
momentjs:1.1.1
monitoring:1.90.0
msbuild:1.30
mstest:1.0.0
next-executions:1.0.15
nodejs:1.5.1
okhttp-api:4.9.3-105.vb96869f8ac3a
opencover:1.0.3
pam-auth:1.6.1
parameterized-trigger:2.43
pipeline-build-step:2.15
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:446.vf27b_0b_83500e
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
plain-credentials:1.7
plugin-util-api:2.12.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
prism-api:1.25.0-2
promoted-builds:3.11
pubsub-light:1.16
resource-disposer:0.17
role-strategy:3.2.0
run-condition:1.5
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
sse-gateway:1.24
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
subversion:2.15.2
synopsys-coverity:3.0.1
token-macro:267.vcdaea6462991
translation:1.16
trilead-api:1.0.13
variant:1.4
versioncolumn:2.2
view-job-filters:2.3
warnings-ng:9.11.0
windows-slaves:1.8
workflow-aggregator:2.6
workflow-api:1136.v7f5f1759dc16
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-durable-task-step:1121.va_65b_d2701486
workflow-job:1145.v7f2433caa07f
workflow-multibranch:706.vd43c65dec013
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
ws-cleanup:0.40
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller & agents are Windows 

### Reproduction steps

Set a project up to checkout with changelog:false
On checkout, observe java.lang.NullPointerException

### Expected Results

Checkout to succeed with no errors

### Actual Results

java.lang.NullPointerException
	at hudson.plugins.accurev.XmlConsolidateStreamChangeLog.getStreamChangeLogFile(XmlConsolidateStreamChangeLog.java:35)
	at hudson.plugins.accurev.delegates.AbstractModeDelegate.getChangesFromStreams(AbstractModeDelegate.java:327)
	at hudson.plugins.accurev.delegates.AbstractModeDelegate.captureChangeLog(AbstractModeDelegate.java:294)
	at hudson.plugins.accurev.delegates.AbstractModeDelegate.checkout(AbstractModeDelegate.java:211)
	at hudson.plugins.accurev.AccurevSCM.checkout(AccurevSCM.java:400)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

### Anything else?

Compared the AccuRev plugin to the Git plugin and saw that in Git there were checks for the `changeLogFile != null` in certain areas.

**Comment by NuvotonMG** [comment]
Hi @nathan-murphy! I'm experiencing this aforementioned issue - and wanted to try your fix. The thing is, I'm experiencing difficulties building the plugin on my system. Can you maybe assist me with this? maybe send me a compiled-for-x64 .hpi file?
You can send it to maor.galkin@nuvoton.com
*Please forgive me in advance if the following request is unorthodox, and/or if this is not the place to ask for such assistance*
